---
- name: Add an apt key by id from a keyserver
  apt_key:
    id: E52529D4
    keyserver: keyserver.ubuntu.com
  tags: install
- name: add apt repo
  apt_repository: 
    repo: deb [ arch=amd64,arm64] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
    state: present
  tags: install
- name: Update packages
  apt:
    update_cache: yes
  tags: install
- name: Install mongodb package
  apt: 
    name: mongodb-org
    state: present
  tags: install
- name: Enable mongodb service
  systemd:
    name: mongod
    state: started
    enabled: yes
  tags: install
